name: "setup-scala"
description: "Installs AdoptOpenJDK via Jabba, and Bloop"
author: "Olafur Pall Geirsson"
inputs:
  java-version:
    description: >
      The Java version to install, a string matching the output format
      from  `jabba ls-remote`. For example, "adopt@1.8" for the latest
      AdoptOpenJDK 8 version, "adopt@1.11" for the latest AdoptOpenJDK 11
      version, or "graalvm@" for the latest GraalVM version.
    default: "adopt@1.8"
  jabba-version:
    description: The Jabba version to install.
    default: "0.11.2"
  bloop-version:
    description: The version of Bloop to install.
    default: "1.4.1"
runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "download"
  color: "blue"
