name: CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn run build
      - uses: ./
      - run: cd test-build && sbt run
        shell: bash
      - run: ls ~/bin
        shell: bash
      - run: cd test-build && sbt bloopInstall && bloop run test-build
        shell: bash
